# Generated by Django 3.2.9 on 2021-11-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='cpc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='cpm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
